# H2 Database Configuration
spring:
    h2:
      console:
          enabled: true
          path: /h2-console
    datasource:
      url: jdbc:h2:file:~/testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
  # JPA/Hibernate Configuration
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
          ddl-auto: create-drop
      show-sql: true
      properties:
          hibernate:
              format_sql: true


  
  # Server Port
server:
  port: 8080